[prune]
  non-go = true
  go-tests = true

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.12.54"

[[constraint]]
  name = "gopkg.in/AlecAivazis/survey.v1"
  version = "1.4.1"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"
